NS = {
    "core": "http://www.opengis.net/citygml/3.0",
    "gml": "http://www.opengis.net/gml/3.2",
    "app": "http://www.opengis.net/citygml/appearance/3.0",
    "brid": "http://www.opengis.net/citygml/bridge/3.0",
    "bldg": "http://www.opengis.net/citygml/building/3.0",
    "fm": "http://www.opengis.net/citygml/cityfurniture/3.0",
    "grp": "http://www.opengis.net/citygml/cityobjectgroup/3.0",
    "con": "http://www.opengis.net/citygml/construction/3.0",
    "dyn": "http://www.opengis.net/citygml/dynamizer/3.0",
    "gen": "http://www.opengis.net/citygml/generics/3.0",
    "luse": "http://www.opengis.net/citygml/landuse/3.0",
    "pcl": "http://www.opengis.net/citygml/pointcloud/3.0",
    "dem": "http://www.opengis.net/citygml/relief/3.0",
    "tran": "http://www.opengis.net/citygml/transportation/3.0",
    "tun": "http://www.opengis.net/citygml/tunnel/3.0",
    "veg": "http://www.opengis.net/citygml/vegetation/3.0",
    "vers": "http://www.opengis.net/citygml/versioning/3.0",
    "wtr": "http://www.opengis.net/citygml/waterbody/3.0",
}